language: ruby
services:
- postgresql
rvm:
- 2.5.0
install:
- gem uninstall bundler
- gem install bundler --version '1.7.4'
- bundle install
- rails db:create
- rails db:migrate
script: rake
deploy:
  skip_cleanup: true
  provider: heroku
  app: gapag1
  api_key:
    secure: Omxhx8WgZsyiY4rpgX4bTW7PK6CADZs4IIfNvB+lMONyp4cVkEMzTAXUJ1VzNHfRvzFaLaya8ArCqtm05dB7L7XOPL99mn9ilk2MvMHnZX64VimubkvgSqN0d+SrRodtLyeNiyXllRyWD7qy5CQR7xzDHGMkD9NwSheI4+5JutkX5Ec6xXdrODyVSZ/BnrXHWizbstfOb7nFHhjvFzmG1K4VdDNSmoSdDQ4vYwXOyIP6JsWjIcZtrxNA+N2Ejsu/fcZKtU/8aHAI1FMozw1wYqtbdFeX2Bh0Qke1p9ZLsHCgiYc0VrOTiXwxj/6kh/bIkIVJviL3uoyDq4Jz/o3BSeBEN2gTKF0VoVi162gZAtaWgkZUqiogjJNL/yxlZL95LM+o7WbfF2iWZMuaP1hE9lt8nZ/CZwDTlqkP+Fh35YVLdLPE+T9EffPcos70q38hl07gxus426rtUAtbArwAGkBnYdlwC3ruJzB4vPYazbjUOCPQHa5cXJnr5Hdk8uUh3JL4ODJvCaa7T/qnCYWDpPDAkgIOFjgEjoR9Miwp2U+EYS1oJiff5f9s9N0LmsYZmWiy7jGb2IgcTNu1CQIyX7x7XBzBJuIsA3J1ITkOaP0WvlxXRNpbNBZz6tLvxq2lpZphgPIoi312TM8U4bf4VCc06qJdB0BcHPXwT9T05ck=
