language: ruby
services:
- postgresql
rvm:
- 2.5.0
install:
- gem uninstall bundler
- gem install bundler --version '1.7.4'
- bundle install
- rails db:create
- rails db:migrate
script: rake
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: HK6tMc1Rm9SOSNeNB2VxU7mj9WJqgt0KIcB7ozA0NzDMzA33vQ1K+0gzLlux6rfLm+N2l75/roSLmiTouQfTYW+7zU2sg70OoRGuXYLNPzxP2p/ZzHkZ4OnCo6fFzuJKn9jWTF1hRqir9cLaWJZvIN/uYhfZi515kEPlwp7E/GD8kqckukRllJ04sKMI9zxufCoQpn5Y21iozQTEk6vTNmQEVcPTG2If5SgVgLmlT5qjL7WUfmQ2iH3mqxAAb1YxG/zm00EBA0skWt8eXVWOR+1uXkw96DCQga5ATz11KqIiREJnqXDTItJUaoFnU6LFfP+2V3PpPjr6DwW2IfXoxLWlP6LEqyf9b+1bxREqVOGGD2+Bo77/DP+Cbw5YAJOodz0Ngcatc1CerXw0/hk1m24eO1jJhuJu/XdYxqUYn/wIOYwq7yJKHDLNoUypNjakIFzanlaQQX270NJJU0GsYTg0ptMZ+GOe7B8hRs9e6JBXffAT965h9dSokwHZQyNPW7caSAyf17jVwG3aLfN82RAQzAtpSlE3aZu+YlNoFGUbzLtObKwzlUkOuEuV+8F6EUo5ULiYbZXbShd1SXPW+/QP7QjmogGYR+oIVD2lApTw/lbSzC+rgEoLv8WiGQ9PuZ75bfvh9u2F96xNX0P/v/JSmW2e+4Q8TmiIanek/GY=
